version: "3.9"
services:
  kafka:
    image: redpandadata/redpanda:latest
    command: redpanda start --overprovisioned --smp 1 --reserve-memory 0M --node-id 0 --check=false
    ports:
      - "9092:9092"
    environment:
      - KAFKA_AUTO_CREATE_TOPICS=true

  relay:
    build: ./packages/relay-kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka

  order-processor:
    build: ./packages/services/order-processor
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
